theme: jekyll-theme-time-minimal
title: Yair Gat
logo: Other/profile.png
show_downloads: false
github:
   is_project_page: false

$(".theme-switch").on("click", () => {
  $("body").toggleClass("light-theme");
});
